services:
  IssuesSynchronizer:
    image: issuessyncronizer
    build:
      context: .
      dockerfile: IssuesSynchronizer/Dockerfile
    environment:
      ConnectionStrings__Main: "Server=postgres;Port=5432;Database=IssuesSynchronizer;User Id=postgres;Password=localpassword;"
      GitHubApi__WebHookSecret: "PASTE VALUE HERE"
      GitHubApi__AppIdentifier: "PASTE VALUE HERE"
      GitHubApi__PrivateKey: "PASTE VALUE HERE"
      GitHubApi__AppName: "PASTE VALUE HERE"
      DiscordBotToken: "PASTE VALUE HERE"
    ports:
      - "8080:8080"
    depends_on:
      - "postgres"
    networks:
      - issuessynchronizer-network
  
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: localpassword
    restart: always
    networks:
      - issuessynchronizer-network

networks:
  issuessynchronizer-network:
    driver: bridge